# Generated by Django 5.1.6 on 2025-02-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_aboutpage_bottom_text_aboutpage_education_subtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='bottom_button_label',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
    ]
