# Generated by Django 5.1.6 on 2025-02-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_blogindexpage_blogpage_blogpagetag_blogpage_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='date',
            field=models.DateField(default='2025-01-01', verbose_name='Post date'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpage',
            name='intro',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
