from config.django.base import LANGUAGES

WAGTAIL_SITE_NAME = "Agir Vie Verte"

WAGTAIL_I18N_ENABLED = True
WAGTAIL_CONTENT_LANGUAGES = LANGUAGES

WAGTAILADMIN_COMMENTS_ENABLED = False

WAGTAIL_AUTO_UPDATE_PREVIEW = True

WAGTAILADMIN_GLOBAL_EDIT_LOCK = True

WAGTAILIMAGES_EXTENSIONS = ["png", "jpg", "svg"]
WAGTAILDOCS_EXTENSIONS = ["pdf", "docx"]

TAGGIT_CASE_INSENSITIVE = False
